using AguasNico_Api.DAL.DB;
using AguasNico_Api.Models;
using Microsoft.EntityFrameworkCore;

namespace AguasNico_Api.DAL;

public class MigrationRunner(APIContext db, IConfiguration config)
{
    private readonly APIContext _db = db;
    private readonly IConfiguration _config = config;

    public async Task Run()
    {
        if (!_config.GetValue("Database:RunSqlMigrations", true))
            return;

        await EnsureMigrationTableExists();

        var migrationsPath = Path.Combine(AppContext.BaseDirectory, "DAL", "Migrations");
        if (!Directory.Exists(migrationsPath))
            migrationsPath = Path.Combine(Directory.GetCurrentDirectory(), "DAL", "Migrations");

        if (!Directory.Exists(migrationsPath))
            return;

        var migrationFiles = Directory
            .EnumerateFiles(migrationsPath, "*.sql")
            .OrderBy(x => x)
            .ToList();

        var executedMigrations = await _db
            .Migration
            .Select(x => x.FileName)
            .ToListAsync();

        foreach (var file in migrationFiles)
        {
            var fileName = Path.GetFileName(file);

            if (executedMigrations.Any(x => x == fileName))
                continue;

            var sql = await File.ReadAllTextAsync(file);
            if (string.IsNullOrWhiteSpace(sql))
                continue;

            await using var tx = await _db.Database.BeginTransactionAsync();

            try
            {
                await _db.Database.ExecuteSqlRawAsync(sql);

                _db.Migration.Add(new Migration
                {
                    FileName = fileName,
                    ExecutedAt = DateTime.UtcNow
                });

                await _db.SaveChangesAsync();
                await tx.CommitAsync();
            }
            catch (Exception)
            {
                await tx.RollbackAsync();
                throw;
            }
        }
    }

    private async Task EnsureMigrationTableExists()
    {
        const string sql = """
            CREATE TABLE IF NOT EXISTS "_Migrations" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "FileName" character varying(260) NOT NULL UNIQUE,
                "ExecutedAt" timestamp with time zone NOT NULL DEFAULT now()
            );
            """;

        await _db.Database.ExecuteSqlRawAsync(sql);
    }
}