CREATE TABLE IF NOT EXISTS "Role" (
    "Id" character varying(450) PRIMARY KEY,
    "Name" character varying(50) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Role_Name" ON "Role" ("Name");

CREATE TABLE IF NOT EXISTS "User" (
    "Id" character varying(450) PRIMARY KEY,
    "RoleId" character varying(450) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(256) NOT NULL,
    "PasswordHash" text NOT NULL,
    "TruckNumber" integer NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_User_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_User_Email" ON "User" ("Email") WHERE "DeletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "IX_User_RoleId" ON "User" ("RoleId");

CREATE TABLE IF NOT EXISTS "Abonos" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL
);

CREATE TABLE IF NOT EXISTS "PaymentMethods" (
    "ID" smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "Products" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(200) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Type" integer NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "IsActive" boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS "Clients" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(200) NOT NULL,
    "Address" character varying(200) NOT NULL,
    "Phone" character varying(200) NOT NULL,
    "Email" character varying(200) NULL,
    "Observations" character varying(300) NULL,
    "Notes" character varying(300) NULL,
    "Debt" numeric(18,2) NOT NULL DEFAULT 0,
    "DealerID" character varying(450) NULL,
    "HasInvoice" boolean NOT NULL DEFAULT false,
    "OnlyAbonos" boolean NOT NULL DEFAULT false,
    "InvoiceType" integer NULL,
    "TaxCondition" integer NULL,
    "CUIT" character varying(11) NULL,
    "DeliveryDay" integer NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "FK_Clients_User_DealerID" FOREIGN KEY ("DealerID") REFERENCES "User" ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_Clients_DealerID" ON "Clients" ("DealerID");

CREATE TABLE IF NOT EXISTS "Expenses" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID" character varying(450) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_Expenses_User_UserID" FOREIGN KEY ("UserID") REFERENCES "User" ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_Expenses_UserID" ON "Expenses" ("UserID");

CREATE TABLE IF NOT EXISTS "Routes" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID" character varying(450) NOT NULL,
    "DayOfWeek" integer NOT NULL,
    "IsStatic" boolean NOT NULL,
    "IsClosed" boolean NOT NULL,
    "DispenserPrice" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_Routes_User_UserID" FOREIGN KEY ("UserID") REFERENCES "User" ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_Routes_UserID" ON "Routes" ("UserID");

CREATE TABLE IF NOT EXISTS "AbonoProducts" (
    "AbonoID" bigint NOT NULL,
    "Type" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_AbonoProducts" PRIMARY KEY ("AbonoID", "Type"),
    CONSTRAINT "FK_AbonoProducts_Abonos_AbonoID" FOREIGN KEY ("AbonoID") REFERENCES "Abonos" ("ID")
);

CREATE TABLE IF NOT EXISTS "AbonoRenewals" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AbonoID" bigint NOT NULL,
    "ClientID" bigint NOT NULL,
    "SettedPrice" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_AbonoRenewals_Abonos_AbonoID" FOREIGN KEY ("AbonoID") REFERENCES "Abonos" ("ID"),
    CONSTRAINT "FK_AbonoRenewals_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID")
);

CREATE INDEX IF NOT EXISTS "IX_AbonoRenewals_AbonoID" ON "AbonoRenewals" ("AbonoID");
CREATE INDEX IF NOT EXISTS "IX_AbonoRenewals_ClientID" ON "AbonoRenewals" ("ClientID");

CREATE TABLE IF NOT EXISTS "ClientAbonos" (
    "ClientID" bigint NOT NULL,
    "AbonoID" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_ClientAbonos" PRIMARY KEY ("ClientID", "AbonoID"),
    CONSTRAINT "FK_ClientAbonos_Abonos_AbonoID" FOREIGN KEY ("AbonoID") REFERENCES "Abonos" ("ID"),
    CONSTRAINT "FK_ClientAbonos_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID")
);

CREATE INDEX IF NOT EXISTS "IX_ClientAbonos_AbonoID" ON "ClientAbonos" ("AbonoID");

CREATE TABLE IF NOT EXISTS "ClientProducts" (
    "ClientID" bigint NOT NULL,
    "ProductID" bigint NOT NULL,
    "Stock" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_ClientProducts" PRIMARY KEY ("ProductID", "ClientID"),
    CONSTRAINT "FK_ClientProducts_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID"),
    CONSTRAINT "FK_ClientProducts_Products_ProductID" FOREIGN KEY ("ProductID") REFERENCES "Products" ("ID")
);

CREATE INDEX IF NOT EXISTS "IX_ClientProducts_ClientID" ON "ClientProducts" ("ClientID");

CREATE TABLE IF NOT EXISTS "Transfers" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClientID" bigint NOT NULL,
    "UserID" character varying(450) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_Transfers_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID"),
    CONSTRAINT "FK_Transfers_User_UserID" FOREIGN KEY ("UserID") REFERENCES "User" ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_Transfers_ClientID" ON "Transfers" ("ClientID");
CREATE INDEX IF NOT EXISTS "IX_Transfers_UserID" ON "Transfers" ("UserID");

CREATE TABLE IF NOT EXISTS "Carts" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClientID" bigint NOT NULL,
    "RouteID" bigint NOT NULL,
    "Priority" integer NOT NULL,
    "State" integer NOT NULL,
    "IsStatic" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_Carts_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID"),
    CONSTRAINT "FK_Carts_Routes_RouteID" FOREIGN KEY ("RouteID") REFERENCES "Routes" ("ID")
);

CREATE INDEX IF NOT EXISTS "IX_Carts_ClientID" ON "Carts" ("ClientID");
CREATE INDEX IF NOT EXISTS "IX_Carts_RouteID" ON "Carts" ("RouteID");

CREATE TABLE IF NOT EXISTS "DispatchedProducts" (
    "RouteID" bigint NOT NULL,
    "Type" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_DispatchedProducts" PRIMARY KEY ("RouteID", "Type"),
    CONSTRAINT "FK_DispatchedProducts_Routes_RouteID" FOREIGN KEY ("RouteID") REFERENCES "Routes" ("ID")
);

CREATE TABLE IF NOT EXISTS "AbonoRenewalProducts" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AbonoRenewalID" bigint NOT NULL,
    "Type" integer NOT NULL,
    "Available" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "FK_AbonoRenewalProducts_AbonoRenewals_AbonoRenewalID" FOREIGN KEY ("AbonoRenewalID") REFERENCES "AbonoRenewals" ("ID")
);

CREATE INDEX IF NOT EXISTS "IX_AbonoRenewalProducts_AbonoRenewalID" ON "AbonoRenewalProducts" ("AbonoRenewalID");

CREATE TABLE IF NOT EXISTS "CartAbonoProducts" (
    "CartID" bigint NOT NULL,
    "Type" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_CartAbonoProducts" PRIMARY KEY ("CartID", "Type"),
    CONSTRAINT "FK_CartAbonoProducts_Carts_CartID" FOREIGN KEY ("CartID") REFERENCES "Carts" ("ID")
);

CREATE TABLE IF NOT EXISTS "CartPaymentMethods" (
    "CartID" bigint NOT NULL,
    "PaymentMethodID" smallint NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_CartPaymentMethods" PRIMARY KEY ("CartID", "PaymentMethodID"),
    CONSTRAINT "FK_CartPaymentMethods_Carts_CartID" FOREIGN KEY ("CartID") REFERENCES "Carts" ("ID"),
    CONSTRAINT "FK_CartPaymentMethods_PaymentMethods_PaymentMethodID" FOREIGN KEY ("PaymentMethodID") REFERENCES "PaymentMethods" ("ID")
);

CREATE INDEX IF NOT EXISTS "IX_CartPaymentMethods_PaymentMethodID" ON "CartPaymentMethods" ("PaymentMethodID");

CREATE TABLE IF NOT EXISTS "CartProducts" (
    "CartID" bigint NOT NULL,
    "Type" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "SettedPrice" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_CartProducts" PRIMARY KEY ("Type", "CartID"),
    CONSTRAINT "FK_CartProducts_Carts_CartID" FOREIGN KEY ("CartID") REFERENCES "Carts" ("ID")
);

CREATE INDEX IF NOT EXISTS "IX_CartProducts_CartID" ON "CartProducts" ("CartID");

CREATE TABLE IF NOT EXISTS "ReturnedProducts" (
    "Type" integer NOT NULL,
    "CartID" bigint NOT NULL,
    "Quantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_ReturnedProducts" PRIMARY KEY ("Type", "CartID"),
    CONSTRAINT "FK_ReturnedProducts_Carts_CartID" FOREIGN KEY ("CartID") REFERENCES "Carts" ("ID")
);

CREATE INDEX IF NOT EXISTS "IX_ReturnedProducts_CartID" ON "ReturnedProducts" ("CartID");


