CREATE TABLE IF NOT EXISTS "Terceros" (
    "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Date" timestamp with time zone NOT NULL,
    "Name" character varying(200) NOT NULL,
    "SodaQuantity" integer NOT NULL DEFAULT 0,
    "SodaAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "B12LQuantity" integer NOT NULL DEFAULT 0,
    "B12LAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "B20LQuantity" integer NOT NULL DEFAULT 0,
    "B20LAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "DeletedAt" timestamp with time zone NULL
);

CREATE INDEX IF NOT EXISTS "IX_Terceros_Date" ON "Terceros" ("Date");
